### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Shivansh-Potdar** [Gkemon/Lovely-Android-Loading#1]
Seems like an amazing library I would like to use it but, there is no documentation. Please do add it.

**Comment by Gkemon** [comment]
Thanks, Shivansh for your query. I will complete it as soon as possible.

**Comment by Shivansh-Potdar** [comment]
Haha, thank you for responding I shall look forward to it.

**Comment by Gkemon** [comment]
I'm working on some very good features for it. Sure it will be helpful you
all much. That's why it takes some time dude.

**Comment by Shivansh-Potdar** [comment]
I hope you're still working on it

**Comment by Gkemon** [comment]
Hi @Shivansh-Potdar, Thanks for poked me and for your push I felt motivated to release it as a library :P . I have just added documentation. Please have a look and feel free to knock me if find any complexity. And sorry for the late reply, because I was so busy with my office work and didn't get proper time to work on this .

**Comment by Shivansh-Potdar** [comment]
thonnobad @Gkemon, I will be using this in future projects 🙏
